import { createHash } from 'node:crypto';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { asset, type AssetScope, type AssetVariants, type Executor } from '@valkyria/db';
import sharp from 'sharp';

/*
 * Original synthetic images for development/test fixtures. Each image is rendered from an
 * SVG (dark gradient, geometric shapes, "SYNTHETIC FIXTURE" plus a label) — never a
 * screenshot, legacy site graphic or design reference. Text uses a built-in stroke
 * font so it renders identically without any system fonts installed.
 */

export const FIXTURE_FILENAME_PREFIX = 'synthetic-fixture-';
export const FIXTURE_PROVENANCE = 'Synthetic development fixture rendered from SVG by apps/web/src/fixtures; not a photo, game asset or real team mark.';
const FIXTURE_RIGHTS = 'Synthetic test image generated by project code; development and test use only.';

/** Glyphs on a 4×6 grid as polylines ("x,y x,y …"); advance is 6 units. */
const GLYPHS: Record<string, string[]> = {
  A: ['0,6 0,2 2,0 4,2 4,6', '0,3.5 4,3.5'],
  B: ['0,0 0,6 3,6 4,5 4,4 3,3 0,3', '0,0 3,0 4,1 4,2 3,3'],
  C: ['4,1 3,0 1,0 0,1 0,5 1,6 3,6 4,5'],
  D: ['0,0 0,6 3,6 4,5 4,1 3,0 0,0'],
  E: ['4,0 0,0 0,6 4,6', '0,3 3,3'],
  F: ['4,0 0,0 0,6', '0,3 3,3'],
  G: ['4,1 3,0 1,0 0,1 0,5 1,6 3,6 4,5 4,3 2,3'],
  H: ['0,0 0,6', '4,0 4,6', '0,3 4,3'],
  I: ['1,0 3,0', '2,0 2,6', '1,6 3,6'],
  J: ['4,0 4,5 3,6 1,6 0,5'],
  K: ['0,0 0,6', '4,0 0,3.5 4,6', '1.2,2.8 4,0'],
  L: ['0,0 0,6 4,6'],
  M: ['0,6 0,0 2,3 4,0 4,6'],
  N: ['0,6 0,0 4,6 4,0'],
  O: ['1,0 3,0 4,1 4,5 3,6 1,6 0,5 0,1 1,0'],
  P: ['0,6 0,0 3,0 4,1 4,2 3,3 0,3'],
  Q: ['1,0 3,0 4,1 4,5 3,6 1,6 0,5 0,1 1,0', '2.5,4.5 4,6'],
  R: ['0,6 0,0 3,0 4,1 4,2 3,3 0,3', '2,3 4,6'],
  S: ['4,1 3,0 1,0 0,1 0,2 1,3 3,3 4,4 4,5 3,6 1,6 0,5'],
  T: ['0,0 4,0', '2,0 2,6'],
  U: ['0,0 0,5 1,6 3,6 4,5 4,0'],
  V: ['0,0 2,6 4,0'],
  W: ['0,0 1,6 2,3 3,6 4,0'],
  X: ['0,0 4,6', '4,0 0,6'],
  Y: ['0,0 2,3 4,0', '2,3 2,6'],
  Z: ['0,0 4,0 0,6 4,6'],
  '0': ['1,0 3,0 4,1 4,5 3,6 1,6 0,5 0,1 1,0', '0.5,5 3.5,1'],
  '1': ['1,1 2,0 2,6', '1,6 3,6'],
  '2': ['0,1 1,0 3,0 4,1 4,2 0,6 4,6'],
  '3': ['0,1 1,0 3,0 4,1 4,2 3,3 4,4 4,5 3,6 1,6 0,5', '1.5,3 3,3'],
  '4': ['3,6 3,0 0,4 4,4'],
  '5': ['4,0 0,0 0,3 3,3 4,4 4,5 3,6 0,6'],
  '6': ['4,1 3,0 1,0 0,1 0,5 1,6 3,6 4,5 4,4 3,3 0,3'],
  '7': ['0,0 4,0 1,6'],
  '8': ['1,3 0,2 0,1 1,0 3,0 4,1 4,2 3,3 1,3 0,4 0,5 1,6 3,6 4,5 4,4 3,3'],
  '9': ['0,5 1,6 3,6 4,5 4,1 3,0 1,0 0,1 0,2 1,3 4,3'],
  '-': ['1,3 3,3'],
  '/': ['0,6 4,0'],
  '.': ['1.8,5.6 2.2,5.6 2.2,6 1.8,6 1.8,5.6'],
  ':': ['1.8,1.6 2.2,1.6 2.2,2 1.8,2 1.8,1.6', '1.8,4.6 2.2,4.6 2.2,5 1.8,5 1.8,4.6'],
  '[': ['3,0 1,0 1,6 3,6'],
  ']': ['1,0 3,0 3,6 1,6'],
};

/** Width in pixels of `text` rendered at glyph height `size`. */
export function strokeTextWidth(text: string, size: number): number {
  const unit = size / 6;
  return Math.max(0, text.length * 6 - 2) * unit;
}

/** SVG path data for `text` (upper-cased; unsupported characters become spaces). */
export function strokeTextPath(text: string, x: number, y: number, size: number): string {
  const unit = size / 6;
  const parts: string[] = [];
  [...text.toUpperCase()].forEach((char, index) => {
    const ox = x + index * 6 * unit;
    for (const line of GLYPHS[char] ?? []) {
      const points = line.split(' ').map((pair) => {
        const [gx, gy] = pair.split(',').map(Number) as [number, number];
        return `${(ox + gx * unit).toFixed(1)},${(y + gy * unit).toFixed(1)}`;
      });
      parts.push(`M${points.join(' L')}`);
    }
  });
  return parts.join(' ');
}

function centeredText(text: string, centerX: number, top: number, size: number, stroke: string, weight: number): string {
  const d = strokeTextPath(text, centerX - strokeTextWidth(text, size) / 2, top, size);
  return `<path d="${d}" fill="none" stroke="${stroke}" stroke-width="${weight}" stroke-linecap="round" stroke-linejoin="round"/>`;
}

export type FixtureImageSpec = {
  id: string;
  /** Stable file-name stem (without prefix/extension). */
  name: string;
  label: string;
  width: number;
  height: number;
  scope: AssetScope;
  colors: [string, string, string];
  altCs: string;
  altEn: string;
};

/** Renders the SVG source for a fixture image. */
export function fixtureSvg(spec: FixtureImageSpec): string {
  const { width: w, height: h, colors } = spec;
  const [dark, mid, accent] = colors;
  const min = Math.min(w, h);
  const title = 'SYNTHETIC FIXTURE';
  const titleSize = Math.min((w * 0.8) / (title.length * 6 - 2) * 6, min * 0.1);
  const labelSize = Math.min((w * 0.7) / Math.max(1, spec.label.length * 6 - 2) * 6, titleSize * 0.7);
  const shapes: string[] = [];
  for (let i = 0; i < 6; i += 1) {
    const cx = ((i * 37) % 100) / 100;
    const cy = ((i * 59) % 100) / 100;
    shapes.push(
      `<polygon points="${(cx * w).toFixed(0)},${(cy * h).toFixed(0)} ${((cx + 0.25) * w).toFixed(0)},${((cy + 0.05) * h).toFixed(0)} ${((cx + 0.1) * w).toFixed(0)},${((cy + 0.3) * h).toFixed(0)}" fill="${accent}" fill-opacity="${(0.06 + i * 0.02).toFixed(2)}"/>`,
    );
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${dark}"/>
      <stop offset="1" stop-color="${mid}"/>
    </linearGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="url(#bg)"/>
  ${shapes.join('\n  ')}
  <circle cx="${w * 0.82}" cy="${h * 0.22}" r="${min * 0.16}" fill="none" stroke="${accent}" stroke-opacity="0.35" stroke-width="${min * 0.012}"/>
  <rect x="${min * 0.04}" y="${min * 0.04}" width="${w - min * 0.08}" height="${h - min * 0.08}" fill="none" stroke="${accent}" stroke-opacity="0.6" stroke-width="${min * 0.01}"/>
  ${centeredText(title, w / 2, h / 2 - titleSize * 1.1, titleSize, '#f5f1e8', Math.max(2, titleSize * 0.12))}
  ${centeredText(spec.label, w / 2, h / 2 + labelSize * 0.6, labelSize, accent, Math.max(2, labelSize * 0.12))}
</svg>`;
}

export function resolveMediaRoot(env: Record<string, string | undefined> = process.env, cwd = process.cwd()): string {
  return path.resolve(cwd, env.EDITORIAL_MEDIA_ROOT?.trim() || '.local/editorial-media');
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** Rasterizes the fixture SVG to the PNG "source upload" bytes. */
export function renderFixturePng(spec: FixtureImageSpec): Promise<Buffer> {
  return sharp(Buffer.from(fixtureSvg(spec))).png({ compressionLevel: 9 }).toBuffer();
}

/** Renders, derives and stores one fixture image; returns the asset row values. */
export async function createFixtureAsset(db: Executor, spec: FixtureImageSpec, mediaRoot: string) {
  if (!UUID.test(spec.id)) throw new Error('Fixture asset IDs must be lowercase UUIDs.');
  const source = await renderFixturePng(spec);
  const full = await sharp(source).resize({ width: 2400, height: 2400, fit: 'inside', withoutEnlargement: true }).webp({ quality: 82 }).toBuffer({ resolveWithObject: true });
  const thumb = await sharp(source).resize({ width: 480, height: 480, fit: 'inside', withoutEnlargement: true }).webp({ quality: 78 }).toBuffer({ resolveWithObject: true });
  const directory = path.join(mediaRoot, spec.id);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, 'full.webp'), full.data);
  await writeFile(path.join(directory, 'thumb.webp'), thumb.data);
  const variants: AssetVariants = {
    full: { key: `${spec.id}/full.webp`, width: full.info.width, height: full.info.height, bytes: full.info.size, mime: 'image/webp' },
    thumb: { key: `${spec.id}/thumb.webp`, width: thumb.info.width, height: thumb.info.height, bytes: thumb.info.size, mime: 'image/webp' },
  };
  await db.insert(asset).values({
    id: spec.id,
    scope: spec.scope,
    state: 'ready',
    originalFilename: `${FIXTURE_FILENAME_PREFIX}${spec.name}.png`,
    sourceFormat: 'png',
    width: spec.width,
    height: spec.height,
    bytes: source.length,
    sha256: createHash('sha256').update(source).digest('hex'),
    variants,
    provenance: FIXTURE_PROVENANCE,
    rights: FIXTURE_RIGHTS,
    defaultAltCs: spec.altCs,
    defaultAltEn: spec.altEn,
  });
  return variants;
}

/** Removes stored files of fixture assets (only UUID-named folders inside the media root). */
export async function removeFixtureFiles(mediaRoot: string, ids: readonly string[]): Promise<void> {
  const root = path.resolve(mediaRoot);
  for (const id of ids) {
    if (!UUID.test(id)) continue;
    const directory = path.resolve(root, id);
    if (path.dirname(directory) !== root) continue;
    await rm(directory, { recursive: true, force: true });
  }
}
